[build]
  functions = "netlify/functions"

[functions]
  included_files = ["private/app.html"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/"
  to = "/.netlify/functions/api"
  status = 200
  force = true
